from ndcctools.taskvine import DaskVine

from ndcctools.taskvine.dagvine import DAGVine
from ndcctools.taskvine.dagvine.blueprint_graph.adaptor import collections_from_blueprint_graph
from ndcctools.taskvine.cvine import vine_manager_get_makespan_us

import analysis_tools

import cloudpickle
import argparse

from graph_generator import *
import graph_generator as _graph_generator  # ensure module object available for hoisting/env transfer
import graph_tasks as _graph_tasks
import ndcctools.taskvine.dagvine.dagvine as _dagvine_mod


def _argparse_action_sort_key(action: argparse.Action):
    # Sort by "parameter name" (dest) to get a..z ordering that is stable
    # regardless of how add_argument() was written.
    if action.dest:
        return str(action.dest).lower()
    # Fallback (shouldn't happen in normal argparse actions).
    if getattr(action, "option_strings", None):
        return str(action.option_strings[0]).lstrip("-").lower()
    return ""


class SortedHelpArgumentParser(argparse.ArgumentParser):
    """
    An ArgumentParser whose -h/--help output lists options in dictionary order
    (a at top, z at bottom).
    """

    def format_help(self) -> str:
        original_group_actions = []
        for group in self._action_groups:
            original_group_actions.append(list(group._group_actions))
            group._group_actions.sort(key=_argparse_action_sort_key)
        try:
            return super().format_help()
        finally:
            for group, original in zip(self._action_groups, original_group_actions):
                group._group_actions[:] = original


rstriphoton_env_files = {
    "./analysis_tools/dataset_info.py" : "analysis_tools/dataset_info.py",
    "./analysis_tools/signal_info.py" : "analysis_tools/signal_info.py",
    "./analysis_tools/storage_config.py" : "analysis_tools/storage_config.py",
    "./analysis_tools/coffea_utils.py" : "analysis_tools/coffea_utils.py",
    "./analysis/variables.py" : "analysis/variables.py",
    "./analysis/selections.py" : "analysis/selections.py",
    "./analysis/calculations.py" : "analysis/calculations.py",
    "./analysis/plotting.py" : "analysis/plotting.py",
    "./analysis_processor.py" : "analysis_processor.py",
}


def main():
    # Override -h/--help: print options sorted a..z (dictionary order).
    parser = SortedHelpArgumentParser(add_help=False)
    parser.add_argument(
        "-h",
        "--help",
        action="help",
        default=argparse.SUPPRESS,
        help="show this help message and exit",
    )
    parser.add_argument("--manager-name", "-M", type=str, default=None)
    parser.add_argument("--task-file", type=str, default=None)
    parser.add_argument(
        "--task-complexity",
        type=int,
        default=1,
        help="Per-task Python function complexity (1..5). Only applies to graphs generated by --graph/-G.",
    )
    parser.add_argument("--libcores", type=int, default=16)
    parser.add_argument("--prune-depth", type=int, default=0)
    parser.add_argument("--temp-replica-count", type=int, default=1)
    parser.add_argument("--immediate-recovery", type=int, default=0)
    parser.add_argument("--wait-for-workers", type=int, default=0)
    parser.add_argument("--max-workers", type=int, default=-1)
    parser.add_argument("--watch-library-logfiles", type=int, default=0)
    parser.add_argument("--enforce-worker-eviction-interval", type=int, default=-1)
    parser.add_argument("--task-priority-mode", type=str, default="random")
    parser.add_argument("--checkpoint-fraction", type=float, default=0)
    parser.add_argument("--scheduling-mode", type=str, default="files")
    parser.add_argument("--run-info-path", type=str, default="/users/jzhou24/afs/taskvine-report-tool/logs/project-dagvine")
    parser.add_argument("--run-info-template", type=str, default="test")
    # For daskvine executors: use a per-run staging directory to avoid collisions when
    # multiple managers run concurrently (otherwise they may overwrite py_wrapper_*).
    parser.add_argument("--staging-path", type=str, default=None)
    parser.add_argument("--shift-disk-load", type=int, default=0)
    parser.add_argument("--output-dir", type=str, default="/project01/ndcms/jzhou24/outputs")
    parser.add_argument("--checkpoint-dir", type=str, default="/project01/ndcms/jzhou24/checkpoints")
    parser.add_argument("--prioritize-recovery-tasks", type=int, default=0)
    parser.add_argument("--clean-redundant-replicas", type=int, default=0)
    parser.add_argument("--max-cores", type=int, default=100000)
    parser.add_argument("--extra-task-output-size-mb", type=str, nargs=2, default=["0", "0"])
    parser.add_argument("--extra-task-sleep-time",type=str, nargs=2, default=["0", "0"])
    parser.add_argument("--failure-injection-step-percent", type=float, default=-1)
    parser.add_argument("--graph-from-log", type=str, default=None)
    parser.add_argument("--extra-serialize-time-sec", type=float, default=0)
    parser.add_argument("--print-results", type=int, default=0)
    parser.add_argument("--executor", "-X", type=str, default="dagvine")
    parser.add_argument("--print-graph-details", type=int, default=0)
    parser.add_argument("--short-timeout", type=int, default=0)
    # Port binding:
    # TaskVine managers bind a listening port from a range. When running many managers
    # concurrently, sharing the same small default range can cause collisions and even
    # trigger segfaults inside native code on some environments. Allow callers to
    # force a unique port per manager.
    parser.add_argument("--port", type=int, default=None)
    # -G takes 1-2 arguments: graph name + optional total_tasks (int)
    parser.add_argument(
        "--graph",
        "-G",
        nargs="+",
        metavar=("GRAPH", "TOTAL_TASKS"),
        default=None,
        help="Graph name and optional total task count.",
    )
    parser.add_argument("--enable-debug-log", type=int, default=1)
    parser.add_argument("--adapt-dask", type=int, default=False)
    parser.add_argument("--auto-recovery", type=int, default=0)
    parser.add_argument("--max-retry-attempts", type=int, default=1000000)
    parser.add_argument("--retry-interval-sec", type=int, default=1)
    parser.add_argument("--time-metrics-filename", type=str, default=None)
    parser.add_argument("--repeats", type=int, default=1)
    args = parser.parse_args()

    # Exactly one graph source must be provided.
    if bool(args.task_file) == bool(args.graph):
        parser.error("Specify exactly one: --task-file OR --graph/-G")

    if args.task_complexity < 1 or args.task_complexity > 5:
        parser.error("--task-complexity must be in [1, 5]")

    # first remove the existing run info template
    import os
    import shutil

    # Avoid TaskVine's TCP catalog update background path (uses fork()).
    # In practice, some environments have shown segfaults when fork() is invoked
    # from a process that may have threads (Python, native libs, optional UIs).
    # UDP updates avoid the TCP background fork path while keeping catalog usage.
    os.environ.setdefault("CATALOG_UPDATE_PROTOCOL", "udp")

    run_info_template_full = os.path.join(args.run_info_path, args.run_info_template)
    if os.path.exists(run_info_template_full):
        shutil.rmtree(run_info_template_full)
        print(f"Removed existing run info template: {run_info_template_full}")

    # Default staging path: isolate by run-info-template to prevent concurrent runs
    # from clobbering each other's staging files.
    if args.staging_path is None:
        # Keep the existing base, but isolate per run.
        args.staging_path = os.path.join("/groups/dthain/users/jzhou24", "staging", args.run_info_template)
    os.makedirs(args.staging_path, exist_ok=True)

    extra_env_files = {}
    hoisting_modules = []
    base_extra_env_files = {}
    base_hoisting_modules = []
    try:
        import coffea
        import coffea.processor.taskvine_executor
        import analysis_processor
        base_hoisting_modules.append(analysis_processor)
        # NOTE: list.append() only takes one argument.
        base_hoisting_modules.extend([coffea, coffea.processor.taskvine_executor])
    except:
        pass

    repo_root = os.path.dirname(os.path.abspath(__file__))

    graph_name = None
    total_tasks = None
    if args.graph:
        graph_tokens = list(args.graph)
        # --graph/-G only supports a single graph name, plus optional total_tasks (int).
        # Keep the "last token is int -> total_tasks" behavior, but disallow graph lists.
        if len(graph_tokens) > 2:
            parser.error("--graph/-G only supports a single GRAPH plus optional TOTAL_TASKS")
        graph_name = graph_tokens[0]
        if len(graph_tokens) == 2:
            try:
                total_tasks = int(graph_tokens[1])
            except (TypeError, ValueError):
                parser.error("--graph/-G TOTAL_TASKS must be an integer")

    def build_graph_by_name(name: str, total_tasks, task_complexity: int):
        extra_env = {}
        extra_hoisting = []

        # Ensure workers can import modules referenced by task arguments.
        # (Particularly important when task kwargs include structured payloads.)
        extra_hoisting.extend([_graph_tasks, _graph_generator])
        extra_env.update(
            {
                "./graph_tasks.py": "graph_tasks.py",
                "./graph_generator.py": "graph_generator.py",
            }
        )

        if name == "chain":
            graph = make_chain_graph(branches=1, chain_len=(total_tasks or 999), task_complexity=task_complexity)
        elif name == "binary-forest":
            graph = make_binary_forest(branches=5, level=8, task_complexity=task_complexity)
        elif name == "individuals":
            graph = make_individuals(num_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "simple":
            graph = make_simple_graph(task_complexity=task_complexity)
        elif name == "dv5-small":
            with open("task-graph-pkls/dv5-small-converted.pkl", "rb") as f:
                graph = cloudpickle.load(f)
        elif name == "dv5-large":
            with open("task-graph-pkls/dv5-large-converted.pkl", "rb") as f:
                graph = cloudpickle.load(f)
        elif name == "rstriphoton":
            extra_hoisting.append(analysis_tools)
            extra_env = dict(rstriphoton_env_files)
            with open("task-graph-pkls/rstriphoton-converted.pkl", "rb") as f:
                graph = cloudpickle.load(f)
        elif name == "topeft":
            with open("task-graph-pkls/topeft-converted.pkl", "rb") as f:
                graph = cloudpickle.load(f)
        elif name == "trivial":
            graph = make_trivial_workflow(total_tasks=(total_tasks or 10000), task_complexity=task_complexity)
        elif name == "stencil":
            graph = make_stencil(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "fft":
            graph = make_fft(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "sweep":
            graph = make_sweep(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "binary-tree":
            graph = make_binary_tree(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "random":
            graph = make_random(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "blast":
            graph = make_blast(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "sipht":
            graph = make_sipht(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "synthetic_scec":
            graph = make_synthetic_scec(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "epigenomics":
            graph = make_epigenomics(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "ligo":
            graph = make_ligo(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        elif name == "montage":
            graph = make_montage(total_tasks=(total_tasks or 1000), task_complexity=task_complexity)
        else:
            parser.error(f"Unknown graph name: {name}")

        return graph, extra_hoisting, extra_env

    graph = None
    label = None
    if args.task_file:
        with open(args.task_file, "rb") as f:
            graph = cloudpickle.load(f)
        hoisting_modules = list(base_hoisting_modules)
        extra_env_files = dict(base_extra_env_files)
        # Use the task file name for consistent log labels.
        label = os.path.basename(args.task_file)
    elif graph_name:
        graph, extra_hoisting, extra_env = build_graph_by_name(graph_name, total_tasks, args.task_complexity)
        hoisting_modules = list(base_hoisting_modules) + list(extra_hoisting)
        extra_env_files = dict(base_extra_env_files)
        extra_env_files.update(extra_env)
        label = graph_name

    if not args.manager_name:
        if args.task_file:
            manager_name = "jzhou24-taskfile"
        else:
            manager_name = f"jzhou24-{graph_name}"
    else:
        manager_name = args.manager_name

    results = None

    if args.executor == "dagvine":
        # Patch DAGVine's worker-side context loader so it can import user modules.
        # By default, DAGVine's context loader just does `cloudpickle.loads(graph_pkl)`,
        # which may require importing `graph_tasks` during unpickling. However, library
        # input files (env_files) are not automatically added to sys.path.
        #
        # We install a safer loader that adds the working directory (and any directory
        # containing shipped .py files) to sys.path before unpickling.
        def _patched_context_loader_func(graph_pkl):
            import os
            import sys
            import cloudpickle

            cwd = os.getcwd()
            if cwd not in sys.path:
                sys.path.insert(0, cwd)

            # If env_files were placed into a subdirectory, add that directory too.
            for fname in ("graph_tasks.py", "graph_generator.py"):
                try:
                    for root, _dirs, files in os.walk(cwd):
                        if fname in files:
                            if root not in sys.path:
                                sys.path.insert(0, root)
                            break
                except Exception:
                    # Best-effort only; fallback is whatever sys.path already has.
                    pass

            graph = cloudpickle.loads(graph_pkl)
            return {"graph": graph}

        _dagvine_mod.context_loader_func = _patched_context_loader_func

        port_range = [9100, 9199] if args.port is None else [args.port, args.port]
        dagvine = DAGVine(
            port_range,
            name=manager_name,
            run_info_path=args.run_info_path,
            run_info_template=args.run_info_template,
        )
        params = {
            "temp-replica-count": args.temp_replica_count,
            "wait-for-workers": args.wait_for_workers,
            "watch-library-logfiles": args.watch_library_logfiles,
            "immediate-recovery": args.immediate_recovery,
            "max-workers": args.max_workers,
            "enforce-worker-eviction-interval": args.enforce_worker_eviction_interval,
            "shift-disk-load": args.shift_disk_load,
            "libcores": args.libcores,
            "failure-injection-step-percent": args.failure_injection_step_percent,
            "prune-depth": args.prune_depth,
            "checkpoint-dir": args.checkpoint_dir,
            "extra-task-output-size-mb": [float(x) for x in args.extra_task_output_size_mb],
            "extra-task-sleep-time": [float(x) for x in args.extra_task_sleep_time],
            "checkpoint-fraction": args.checkpoint_fraction,
            "output-dir": args.output_dir,
            "progress-bar-update-interval-sec": 0.5,
            "enable-debug-log": args.enable_debug_log,
            "auto-recovery": args.auto_recovery,
            "max-retry-attempts": args.max_retry_attempts,
            "retry-interval-sec": args.retry_interval_sec,
            "time-metrics-filename": args.time_metrics_filename,
            "max-cores": args.max_cores,
            "short-timeout": args.short_timeout,
            "print-graph-details": args.print_graph_details,
        }
        # Ensure deterministic dictionary order (a..z) for any params output/logging.
        params = dict(sorted(params.items(), key=lambda kv: kv[0]))
        dagvine.update_params(params)
        if hasattr(graph, "task_dict") and ("output" in graph.task_dict):
            target_keys = ["output"]
        else:
            target_keys = []

        # CRITICAL:
        # DAGVine loads the Python graph inside a worker-side "context loader" via
        # `cloudpickle.loads(graph_pkl)` (see ndcctools.taskvine.dagvine.dagvine.context_loader_func).
        # That unpickle happens before any user env_files/hoisting_modules can reliably make
        # local modules importable on the worker's sys.path. Therefore, if the graph references
        # our local modules (e.g. functions from `graph_tasks`), workers may fail with:
        #   ModuleNotFoundError: No module named 'graph_tasks'
        #
        # Fix: force cloudpickle to pickle these modules "by value" so unpickling does not
        # require importing them by module name on the worker.
        if hasattr(cloudpickle, "register_pickle_by_value"):
            try:
                cloudpickle.register_pickle_by_value(_graph_tasks)
                cloudpickle.register_pickle_by_value(_graph_generator)
            except Exception:
                # Best-effort: if registration fails for any reason, fall back to
                # the env_files/hoisting_modules mechanism.
                pass

        results = dagvine.run(
            graph,
            target_keys=target_keys,
            hoisting_modules=hoisting_modules,
            env_files=extra_env_files,
            adapt_dask=args.adapt_dask,
            repeats=args.repeats,
        )
        print(f"[{label}] Makespan: {results['Makespan']} seconds")
        print(f"[{label}] Throughput: {results['Throughput']} tasks/s")

    else:
        if not isinstance(graph, BlueprintGraph):
            bg = BlueprintGraph()
            for k, v in graph.items():
                f, a, kwa = v
                bg.add_task(k, f, *a, **kwa)
            graph = bg
        graph = collections_from_blueprint_graph(graph)
        port_range = [9100, 9190] if args.port is None else [args.port, args.port]
        m = DaskVine(
            port_range,
            name=manager_name,
            run_info_path=args.run_info_path,
            run_info_template=args.run_info_template,
            staging_path=args.staging_path,
        )
        m.tune("wait-for-workers", args.wait_for_workers)
        m.tune("enable-debug-log", args.enable_debug_log)
        m.tune("attempt-schedule-depth", 100000)
        m.tune("shift-disk-load", args.shift_disk_load)
        m.tune("clean-redundant-replicas", args.clean_redundant_replicas)
        m.tune("max-retrievals", 10000000)
        m.tune("prefer-dispatch", 1)
        m.tune("worker-source-max-transfers", 1000)
        m.tune("temp-replica-count", args.temp_replica_count)
        m.tune("watch-library-logfiles", args.watch_library_logfiles)
        if "output" in graph:
            target_keys = ["output"]
        else:
            target_keys = []
        if args.executor == "daskvine-functioncall":
            results = m.get(graph, 
                            resources={"cores": 1}, 
                            keys=target_keys, 
                            lib_resources={'cores': args.libcores, 'slots': args.libcores}, 
                            worker_transfers=True, 
                            task_mode="function-calls", 
                            scheduling_mode=args.scheduling_mode,
                            extra_serialize_time_sec=args.extra_serialize_time_sec,
                            # Avoid spawning Rich background refresh threads.
                            # TaskVine's catalog update path uses fork(); calling fork in a
                            # multi-threaded process is fragile and has been observed to
                            # segfault on some systems.
                            progress_disable=True,
                            )
        elif args.executor == "daskvine-pythontask":
            results = m.get(graph, 
                            resources={"cores": 1}, 
                            keys=target_keys, 
                            worker_transfers=True, 
                            task_mode="tasks", 
                            scheduling_mode=args.scheduling_mode,
                            extra_serialize_time_sec=args.extra_serialize_time_sec,
                            # See note above: keep the process single-threaded if possible.
                            progress_disable=True,
                            )
        makespan_s = vine_manager_get_makespan_us(m._taskvine) / 1e6
        throughput = round(len(graph) / makespan_s, 6)
        # Match dagvine format exactly (capitalization + bracketed label).
        print(f"[{label}] Makespan: {makespan_s} seconds")
        print(f"[{label}] Throughput: {throughput} tasks/s")
        
    if args.print_results:
        if results:
            print(f"results = {results}")

if __name__ == "__main__":
    main()
